---
- name: Install required packages
  yum:
   name: "{{ item }}"
   state: present
  with_items:
    - java-1.8.0-openjdk-devel.x86_64
    - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-x86_64.rpm
    - unzip
